package com.example.lee.deme_two;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.lee.deme_two.data.DataBase;

import com.example.lee.deme_two.DataBaseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataBaseDaoConfig;

    private final DataBaseDao dataBaseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataBaseDaoConfig = daoConfigMap.get(DataBaseDao.class).clone();
        dataBaseDaoConfig.initIdentityScope(type);

        dataBaseDao = new DataBaseDao(dataBaseDaoConfig, this);

        registerDao(DataBase.class, dataBaseDao);
    }
    
    public void clear() {
        dataBaseDaoConfig.clearIdentityScope();
    }

    public DataBaseDao getDataBaseDao() {
        return dataBaseDao;
    }

}
